[msbuild]
project = "Pepelax.Extensions.Logging.SpectreConsole.sln"
[github]
user = "pepelax"
repo = "Pepelax.Extensions.Logging.SpectreConsole"
[changelog]
owners = "xoofx" # Exclude xoofx from changelog mentions
[coverage]
exclude = ["[*]Wcwidth.*"]